### ISSUE TITLE
tls.rejectUnauthorized does not work with self-signed/Mumble-CA certs

### ISSUE THREAD

**Issue by jeyemwey** [Johni0702/mumble-client-tcp#1]
Hi, I'd love to use your library in my projects, however my server only has a self-signed certificate. According to StackOverflow, this is how you tell TLS that it should not care about the cert signer:

```js
const connect = require("mumble-client-tcp")
const fs = require("fs")

// Ignore all TLS errors
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0"

connect("paulsurrey.de", 64738, {
	tls: {
		key: fs.readFileSync('key.pem'),
		cert: fs.readFileSync('cert.pem'),
		rejectUnauthorized: false // Ignore TLS errors in this connection
	},
	username: "Google Assistant",
	password: ""
  })
  .done((client) => { // log all users in the Root channel
    client.self.setChannel(client.getChannel("Root"))

    console.log(client.users.map(u => u.username))
  });
```

However, when running this modified code, it still crashes:

```
/app/node_modules/promise/lib/done.js:10
      throw err;
      ^
DEPTH_ZERO_SELF_SIGNED_CERT
```

Can you help me in any way to connect to the server? THANK YOU!

**Comment by Johni0702** [comment]
Ah, yes, the event handler for `secureConnect` gets called regardless of whether the connection is actually secure (great name) and you have to check yourself, which [is what I did](https://github.com/Johni0702/mumble-client-tcp/blob/master/src/index.js#L10). I probably need to handle the `rejectUnauthorized` option manually then. I'll try to push a fix for that next weekend.

Side note: Unless you've got a very good reason not to, you should totally get yourself a not-self-signed certificate. You can get one for free and in an automated way from [Let's Encrypt](https://letsencrypt.org/).

**Comment by jeyemwey** [comment]
I think, it would be enough to change [this line](https://github.com/Johni0702/mumble-client-tcp/blob/master/src/index.js#L10) to `if (socket.authorized || !options.tls.rejectUnauthorized) {`.

I know that and all of my traffic is encrypted with Let's Encrypt, but the Mumble Server hoster is too lazy 😩
